added files for the loading, start working on route

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -10,8 +10,6 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
-    - name: Make script executable
-      run: chmod +x ./load_tweets_parallel.sh
 
     - name: docker
       run: |
@@ -38,9 +36,19 @@ jobs:
         docker compose logs web
        
         # load test data 
-        ./load_tweets_parallel.sh
         # run test cases
-        
+        # Run insert test
+        echo "Running insert test..."
+        docker exec -u postgres final_website-db-1 \
+        psql -U postgres -d postgres -f /test-sql/load_tweets.sql
+
+        # Check exit status
+        if [ $? -eq 0 ]; then
+            echo "✅ Insert test passed"
+        else
+            echo "❌ Insert test failed"
+            exit 1
+        fi       
         # after the database starts successfully,
         # it needs time to load the pagila data;
         # this should happen in <1 second,
